server:
  port: 8080
spring:
  main:
    allow-circular-references: true
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: yaron
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
jwt:
  secret: your_jwt_secret_key
  expiration: 3600000